### ISSUE TITLE
Add option to allow selecting of duplicate multi value options

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#1057]
## Notes
The new option will be present only for `single input` and `input for each value` options in the `multiple value input type` section for the fields select, user and record. When the option is enabled, duplicates are allowed, else they aren't. This option isn't present for `multiple select` because vue-select prevents duplicates for multi value fields

## Todo
- [x] Add option on FE
- [x] Add option on BE
- [x] Apply it to User
- [x] Apply it to Select
- [x] Apply it to Record
- [x] Test FE with BE

**Comment by katrinDY** [comment]
Vue-select doesn't allow duplicate multi values. This option will be added to multi fields of type each and default

**Comment by katrinDY** [comment]
Update: BE has already been added by Denis. Vivek is currently researching why the option (isUniqueMultiValue) is disabled by default. We want it to be enabled => values should not be unique by default

**Comment by katrinDY** [comment]
Update: FE will sync with the default value of isUniqueMultiValue on BE

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that everything works as expected.

**Comment by Bojan-Svirkov** [comment]
Added CL:

```
Added:

{
      "what": [
        "option to allow duplicate values for single and multi value user, record and select fields."
      ],
      "why": [
        "to allow user to have more control over their selections and whether they will be allowing duplicate values or not."
      ],
      "refs": [
        "https://github.com/cortezaproject/corteza/pull/1136/commits/9a2bc8c31aa6623a4f525711722ea09e24bfb3f2"
      ]
    }
