### ISSUE TITLE
Corteza Studio v2 (Dark mode)

### ISSUE THREAD

**Issue by Fajfa** [cortezaproject/corteza#1494]
Implement dark mode, and extra configuration options for studio, alongside possible fixes(if needed).

### Todos
- [x] Ensure that dart-sass installation is not checked  on every request on `custom.css`.
- [x] Add an option to return to original setting 
- [x] Add a switch to light/dark mode
- [x] Add tabs for the themes, 2 for branding [light, dark] and 3 for Custom CSS [`general, light, dark`].
- [x] Add support for light/dark theme
