### ISSUE TITLE
Support for Microsoft SQL Server [PlanID: 2023.3/39/2.6]

### ISSUE THREAD

**Issue by darh** [cortezaproject/corteza#453]
Add support for Microsoft SQL Server for primary store and DAL by extending set of store RDBMS drivers.

Docker images: 
https://hub.docker.com/_/microsoft-mssql-server

Go client lib, provided by MS
https://github.com/microsoft/go-mssqldb

Compatibility check (min 2019):
 - [x] Test with 2017-latest version and record results
 - [x] Test with 2019-latest version and record results
 - [x] Test with 2022-latest version and record results

TODO:

- [x] Figure out how to replace `TRUE`/`FALSE` when building page cursors (MSSQL doesn't support them) with either an expression or modified cursor
- [x] Figure out how to modify `stateFalseComparison` to use the correct `1`/`0` bits instead of the `true`/`false` which goqu doesn't convert
    * I brought in the dialect options which should be good enough for right now; might be better off to make a nuance to produce these _special_ expressions

**Comment by tjerman** [comment]
I'm currently experimenting and struggling with a few parts specific to MS SQL and how the rest of our code is implemented.

MS SQL:

* Issues with using the newer https://github.com/microsoft/go-mssqldb lib; temporarily replaced with the original one (not the fork)
* value placeholders where the expression looks like `some_col IN @3` where the variable would hold `NULL` -- it's erroring out the query
* using value placeholders in expressions like this https://stackoverflow.com/a/15396779 -- it's throwing the values are not defined even tho I define them

Corteza:

* Figuring out the store code to understand it better so I can produce a better result

**Comment by tjerman** [comment]
I have Corteza provisioning for the 2022, 2019, and 2017 versions.

I got stuck on some aggregation issue where the expression used in the group by isn't treated the same as the one in select when I use variables.

Need to get the code cleaned up and then I can push the first version

**Comment by tjerman** [comment]
<deleted>

**Comment by tjerman** [comment]
Notes for setup/testing

`docker-compose.yml`

**IMPORTANT** The port incrementation doesn't exactly match the mssql version incrementation -- why? Yes.

```yml
  mssql_2022:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: on-failure
    ports: [ "127.0.0.1:17081:1433" ]
    volumes:
      - "dbdata_mssql_2022:/var/opt/mssql"
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=I1VcSa69E1

  mssql_2017:
    image: mcr.microsoft.com/mssql/server:2017-latest
    restart: on-failure
    ports: [ "127.0.0.1:17082:1433" ]
    volumes:
      - "dbdata_mssql_2017:/var/opt/mssql"
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=I1VcSa69E1

  mssql_2019:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: on-failure
    ports: [ "127.0.0.1:17083:1433" ]
    volumes:
      - "dbdata_mssql_2019:/var/opt/mssql"
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=I1VcSa69E1
```

`.env`

```env
# 2022
DB_DSN=sqlserver://sa:I1VcSa69E1@localhost:17081?database=corteza
# 2019
# DB_DSN=sqlserver://sa:I1VcSa69E1@localhost:17083?database=corteza
# 2017
# DB_DSN=sqlserver://sa:I1VcSa69E1@localhost:17082?database=corteza
```

To interact with the mssql container

```shell
# ssh into the container
docker compose exec mssql_2022 bash

# log into the prompt
/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P "I1VcSa69E1"
```

**Comment by tjerman** [comment]
I'm currently figuring out how I should handle paging cursors to adjust them for MSSQL needs

**Comment by tjerman** [comment]
Jumped onto the Nylas integration ticket. Will continue after it's done

**Comment by tjerman** [comment]
MS SQL should now be supported in Corteza. I'll need to do a bit of refactoring, cleaning through the following sprints but it is there and it should work as expected.

## Current limitations

* DAL pipeline aggregation will be solved in the application level due to how the aggregation query is constructed and how MSSQL treats variables as different columns (constraint issues)

## TODO improvements

These will be split into new tickets and done in future sprints; they aren't too critical.

**Update**: The checklist was moved into separate tickets; you can ignore it

- [ ] Add the `sqlserver+debug` DSN option. The package doesn't expose appropriate methods so the existing facility can't be used.
- [ ] Investigate "sometimes it just freezes and I have to drop the DB and make a fresh one or wait for a long time". I haven't found a consistent reproduction scenario so I'm betting that this is a me issue.
- [ ] Storing empty workflow `meta` stores `'null'` (a string) instead of a `NULL`. This happens because JSON strings get stored as plain text in MSSQL (probably)
- [ ] Check if we can make boolean casting from JSON columns less insane (`store/adapters/rdbms/drivers/mssql/dialect.go:274`); the whole query firstly checks validity, then handles boolean constants as strings (that is how we get them) and lastly as bits (0/1)
- [ ] Investigate if we can offload that awkward bool conversion somewhere closer to the DB driver. Right now I pass the dialect into the functions that need to work with it, or I replace boolean constants with expressions.

**Comment by tjerman** [comment]
Will merge the PR after the broken version branch tests get resolved.
Will move the above check list into a separate ticket as they're more of a quality of life/improvements/tweaks.

**Comment by tjerman** [comment]
@Bojan-Svirkov I think we should skip the QA for this ticket since it'll sort of get self tested while people are working on their tasks

**Comment by Bojan-Svirkov** [comment]
@tjerman You know the best for this ticket, so if that is your suggestion feel free to move it straight to **Done**.
