### ISSUE TITLE
Archive all legacy repositories

### ISSUE THREAD

**Issue by darh** [cortezaproject/corteza#501]
Due to open PRs and comments, we're holding back on achieving some repositories.

 - [x] [webapp compose](/cortezaproject/corteza-webapp-compose/pulls)
    - [x] cortezaproject/corteza-webapp-compose#454 
    - [x] cortezaproject/corteza-webapp-compose#453
    - [x] cortezaproject/corteza-webapp-compose#451 
    - [x] cortezaproject/corteza-webapp-compose#450 
    - [x] cortezaproject/corteza-webapp-compose#449 
    - [x] cortezaproject/corteza-webapp-compose#454 
    - [x] cortezaproject/corteza-webapp-compose#444 
    - [x] cortezaproject/corteza-webapp-compose#443
 - [x] [webapp admin](/cortezaproject/corteza-webapp-admin/pulls)
    - [x] cortezaproject/corteza-webapp-admin#131
 - [x] [webapp discovery](/cortezaproject/corteza-webapp-discovery/pulls)
 - [x] [webapp workflow](/cortezaproject/corteza-webapp-workflow/pulls)
 - [x] [webapp reporter](/cortezaproject/corteza-webapp-reporter/pulls)
    - [x] cortezaproject/corteza-webapp-reporter#38
 - [x] [webapp privacy](/cortezaproject/corteza-webapp-privacy/pulls)
 - [x] [webapp one](/cortezaproject/corteza-webapp-one/pulls)
 - [x] [js](/cortezaproject/corteza-js/pulls)
   - [x]  cortezaproject/corteza-js#74
 - [x] [vue](/cortezaproject/corteza-vue/pulls)

**Comment by darh** [comment]
test

**Comment by darh** [comment]
testt

**Comment by darh** [comment]
test agai
