### ISSUE TITLE
Integration gateway UI cleanup [PlanID: 2023.3/45/1.7]

### ISSUE THREAD

**Issue by petergrlica** [cortezaproject/corteza#522]
## Route details

**Frontend**

- [x] add description field

**Backend**

- [x] add description field

## Route list

**Frontend**

- [x] [route list consistency](https://github.com/cortezaproject/corteza/issues/518)
- [x] [sort apigw filters](https://github.com/cortezaproject/corteza/issues/519)
- [x] lower-case the `Deleted routes` filter label

## Profiler

**Frontend**
- [x] add padding below body on profiler hit details (this is a general layout foo on admin, so it should be fixed by fixing that)
- [x] change edit icon on aggregations/route list to something more informative
- [x] add text description on alt on (edit) icons
- [x] add bytes to Content Length on hit details
- [x] [implement purging of old profiler hits](https://github.com/cortezaproject/corteza/issues/520)

**Backend**
- [x] [implement purging of old profiler hits](https://github.com/cortezaproject/corteza/issues/520)
- [x] fix "load more" info on 0 remaining items
- [x] [add global integration gateway profiler setting](https://github.com/cortezaproject/corteza/issues/521)

**Comment by petergrlica** [comment]
# Changelog Entry

## Added
### What was added
Route description field
Filters sorting
Profiler hits purging
Integration gateway settings

### Why was it added?
Route description field
 - To be able to have a more verbose description of the endpoint
Integration gateway settings
Filters sorting
 - Sorting was needed in order to be able to perform profiler prefilter before any authentication validators (if needed).
Profiler hits purging
 - Hits can be purged now to facilitate easier route development
Integration gateway settings
 - Added because changing integration gateway settings without server restart is much needed.

## Fixed
### What was fixed
Profiler hits paging
Various UI fixes

### Why was it fixed?
Profiler hits paging
 - The button "load more" was not disabled when there were more hits
