### ISSUE TITLE
Add more options for user to configurate echarts

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#537]
# TODO:
### overlapping labels
- [x] custom formatting of labels
- [x] hide labels
- [x] show labels on chart partitions
- [x] show labels next  to chart partition
- [x] explore other options

### legend
- [x] show/hide
- [x] type of legend - plain, scroll
- [x] explore if top, right, bottom, left cane be set as numbers
- [x] explore other options

### labels
- [x] show
- [x] hide
- [x] rotate

### offset
- [x] add margin
- [x] add padding - can only be added to text
- [x] explore options

## Finishing touches
- [x] tweak UI
- [x] testing
- [x] add translations

---

# Code:
### branch 2022.9.x-feature-echarts-improvements-backup

https://github.com/cortezaproject/corteza/pull/563

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that everything is spot on. @katrinDY the only thing now left is the `changelog` part.

**Comment by katrinDY** [comment]
@Bojan-Svirkov

CL

Added

what: Extended configuration for pie, bar, line and doughnut charts. Three new sections were added - tooltip, legend and offset as well as the options to rotate x and y axis labels (only for bar and line charts).

why: To give the users more freedom to customize charts.

refs: 
- https://github.com/cortezaproject/corteza/commit/a8d3b831db94538f6cfd84bd86fe35ec555b1bc7
- https://github.com/cortezaproject/corteza/commit/b2c9de57a73c84aa16f255e8f7c281be91c76c34

**Comment by Bojan-Svirkov** [comment]
Added CL entry. @katrinDY If everything is merged (and I think it is) feel free to close the issue.
