### ISSUE TITLE
Records not displayed after being imported

### ISSUE THREAD

**Issue by katrinDY** [cortezaproject/corteza#625]
## Issue
![Image](https://user-images.githubusercontent.com/85161724/206726342-d04979a4-db8b-4ad4-858b-3a9dd496dae1.gif)

## TODO
- [x] show records after import
- [x] do the same for namespace in namespace manage
- [x] do the same for chart and module

**Comment by Bojan-Svirkov** [comment]
Tested and confirming that this now works as expected. The only thing left now is the CL entry.

**Comment by katrinDY** [comment]
CL

Fixed

What: Resource list is updated after a new resource is imported

How: An update function was added that re-fetched the list of resources

Refs:
[22.9](https://github.com/cortezaproject/corteza/commit/f2f90325bf60e98645a60d0465d3208c0a995e6a)
[23.3](https://github.com/cortezaproject/corteza/commit/ad9342e15bebf622b9add5ba52654ff2e0b0d06c)

**Comment by Bojan-Svirkov** [comment]
Added CL entry.
